### ISSUE TITLE
Relax framework requirements?

### ISSUE THREAD

**Issue by spekulatius** [toastnz/open-graph-meta#4]
Hello @danaenz 

I noticed the open graph module is locked down for <3.4 Would it be possible to relax this? I had a quick test on my current project and couldn't find any issues.

Peter

**Comment by danaenz** [comment]
Hi @spekulatius 

I've made a few improvements to the module. You'll find the updates tracking along the 0.1 tag.

Major changes:

- The extension has been shifted from Page to Sitetree. For existing sites, run the `MigrateSiteTreeOpenGraphTask` to migrate the data across. Since you're upgrading, you can pass the `?overwrite=1` variable.
- You don't need to use the `<% include OpenGraphMeta %>` in your template - it will inherently add the right tags to the `$MetaTags` variable in your template.
- Included requirement for CMS (uses SiteTree and SiteConfig)
- Relaxed requirements for Framework/CMS

**Comment by spekulatius** [comment]
Thanks @danaenz! Nice enhancements!
